export enum UserRequirement {
  Nationality = 'Nationality',
  BVN = 'BVN (Bank Verification Number)',
  FaceVerification = 'Face Verification',
  ResidentialAddress = 'Residential Address',
  OptionalBusinessDetails = '(Optional) Business Details',
  NIN = 'NIN (National ID Number)',
  NextOfKin = 'Next of Kin',
  ResidentialAddressVerification = 'Residential Address Verification',
  SignedIndemnityForm = 'Signed Indemnity Form',
  CACCertificate = 'CAC Business Registration Certificate',
  BusinessVerificationDocs = 'Business Verification Documents',
  BusinessNameReview = 'Business Name Review',
  Attestation = 'Attestation',
  AdvancedBusinessReview = 'Advanced business review',
  InternalComplianceApproval = 'Internal compliance approval',
}
