export enum AuthErrorEnum {
  CHALLENGE_CREATION_FAILED = 'CHALLENGE_CREATION_FAILED',
  INVALID_OR_EXPIRED_CHALLENGE = 'INVALID_OR_EXPIRED_CHALLENGE',
  REGISTRATION_VERIFICATION_FAILED = 'REGISTRATION_VERIFICATION_FAILED',
  NO_DEVICES_FOUND = 'NO_DEVICES_FOUND',
  DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  VERIFICATION_FAILED = 'VERIFICATION_FAILED',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
