export enum NotificationsEnum {
  // User actions
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_LOGGED_OUT = 'USER_LOGGED_OUT',
  ACCOUNT_UPDATED = 'ACCOUNT_UPDATED',

  // Payment and transaction updates
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',

  // POS specific
  POS_SESSION_STARTED = 'POS_SESSION_STARTED',
  POS_SESSION_ENDED = 'POS_SESSION_ENDED',
  POS_DEVICE_CONNECTED = 'POS_DEVICE_CONNECTED',
  POS_DEVICE_DISCONNECTED = 'POS_DEVICE_DISCONNECTED',

  // Order related
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',

  // Wallet/crypto
  CRYPTO_DEPOSIT_SUCCESSFUL = 'CRYPTO_DEPOSIT_SUCCESSFUL',
  CRYPTO_WITHDRAWAL_SUCCESSFUL = 'CRYPTO_WITHDRAWAL_SUCCESSFUL',
  CRYPTO_WITHDRAWAL_FAILED = 'CRYPTO_WITHDRAWAL_FAILED',

  // Admin/system
  NEW_DEVICE_REGISTERED = 'NEW_DEVICE_REGISTERED',
  SYSTEM_MAINTENANCE = 'SYSTEM_MAINTENANCE',
}

export enum NotificationErrors {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  CREATE_FAILED = 'CREATE_FAILED',
  SAVE_FAILED = 'SAVE_FAILED',
  UPDATE_FAILED = 'UPDATE_FAILED',
  DELETE_FAILED = 'DELETE_FAILED',
}
