export enum QWalletWebhookEnum {
  INVALID_USER = 'INVALID_USER',
  INVALID_CURRENCY = 'INVALID_CURRENCY',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  DUPLICATE_TRANSACTION = 'DUPLICATE_TRANSACTION',
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  NETWORK_NOT_SUPPORTED = 'NETWORK_NOT_SUPPORTED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  TRANSACTION_NOT_CONFIRMED = 'TRANSACTION_NOT_CONFIRMED',
  UNSUPPORTED_EVENT = 'UNSUPPORTED_EVENT',
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',
  MISSING_REQUIRED_FIELDS = 'MISSING_REQUIRED_FIELDS',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
