export interface Bank {
  name: string;
  slug: string;
  code: string;
  ussd: string;
  logo: string;
}

export const NigeriaBanks = [
  {
    name: '3Line Card Management Limited',
    slug: '',
    code: '800',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: '78 Finance Company Limited (Bank78)',
    slug: '',
    code: '245',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: '9 Payment Service Bank',
    slug: '',
    code: '316',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: '9 Payment Service Bank (9PSB)',
    slug: '',
    code: '316',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Aaa Finance',
    slug: '',
    code: '268',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Abbey Mortgage Bank',
    slug: '',
    code: '293',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'AB Microfinance Bank',
    slug: '',
    code: '423',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Above Only Microfinance Bank',
    slug: '',
    code: '413',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Abucoop Microfinance Bank',
    slug: '',
    code: '544',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Abulesoro Microfinance Bank Ltd',
    slug: '',
    code: '659',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'ABU Microfinance Bank',
    slug: '',
    code: '402',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Accelerex Network',
    slug: '',
    code: '405',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Access Bank',
    slug: 'access-bank',
    code: '044',
    ussd: '*901#',
    logo: 'https://nigerianbanks.xyz/logo/access-bank.png',
  },
  {
    name: 'Access Bank (Diamond)',
    slug: 'access-bank-diamond',
    code: '063',
    ussd: '*426#',
    logo: 'https://nigerianbanks.xyz/logo/access-bank-diamond.png',
  },
  {
    name: 'AccessMobile',
    slug: '',
    code: '769',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Accion Microfinance Bank',
    slug: '',
    code: '342',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ada Microfinance Bank',
    slug: '',
    code: '599',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Addosser Microfinance Bank',
    slug: '',
    code: '368',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Adeyemi College Staff Microfinance Bank',
    slug: '',
    code: '421',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Advancly MFB',
    slug: '',
    code: '847',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Afekhafe Microfinance Bank',
    slug: '',
    code: '443',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Afemai Microfinance Bank',
    slug: '',
    code: '634',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'AG Mortgage Bank',
    slug: '',
    code: '784',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Agosasa Microfinance Bank',
    slug: '',
    code: '498',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Akpo Microfinance Bank',
    slug: '',
    code: '712',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Akuchukwu Microfinance Bank Ltd',
    slug: '',
    code: '675',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Aku Microfinance Bank',
    slug: '',
    code: '646',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Akwa Savings & Loans Limited',
    slug: '',
    code: '306',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'AL-Barakah Microfinance Bank',
    slug: '',
    code: '341',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'ALAT by WEMA',
    slug: 'alat-by-wema',
    code: '035A',
    ussd: '*945*100#',
    logo: 'https://nigerianbanks.xyz/logo/alat-by-wema.png',
  },
  {
    name: 'Alekun Microfinance Bank',
    slug: '',
    code: '412',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Alert Microfinance Bank',
    slug: '',
    code: '448',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Al-Hayat Microfinance Bank',
    slug: '',
    code: '430',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Allworkers Microfinance Bank',
    slug: '',
    code: '339',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ally Microfinance Bank',
    slug: '',
    code: '662',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Alpha Kapital Microfinance Bank',
    slug: '',
    code: '377',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Alternative Bank Limited',
    slug: '',
    code: '256',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Alvana Microfinance Bank',
    slug: '',
    code: '605',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Amac Microfinance Bank',
    slug: '',
    code: '515',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'AMJU Unique Microfinance Bank',
    slug: '',
    code: '389',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'AMML MFB',
    slug: '',
    code: '324',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Amoye Microfinance Bank',
    slug: '',
    code: '714',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ample MFB',
    slug: '',
    code: '853',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Anchorage Microfinance Bank',
    slug: '',
    code: '592',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Aniocha Microfinance Bank',
    slug: '',
    code: '585',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Apeks Microfinance Bank',
    slug: '',
    code: '351',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Apex Trust MFB',
    slug: '',
    code: '749',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Apple Microfinance Bank',
    slug: '',
    code: '502',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Aramoko Microfinance Bank',
    slug: '',
    code: '455',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Arca Payments',
    slug: '',
    code: '806',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Arise Microfinance Bank',
    slug: '',
    code: '435',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'ASO Savings and Loans',
    slug: 'asosavings',
    code: '401',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/asosavings.png',
  },
  {
    name: 'Aspire Microfinance Bank Ltd',
    slug: '',
    code: '658',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Assets Matrix Microfinance Bank',
    slug: '',
    code: '439',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Assets Microfinance Bank',
    slug: '',
    code: '589',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Astrapolaris Microfinance Bank',
    slug: '',
    code: '380',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Atbu Microfinance Bank',
    slug: '',
    code: '569',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Auchi Microfinance Bank',
    slug: '',
    code: '417',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ave Maria Microfinance Bank Ltd',
    slug: '',
    code: '707',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Avuenegbe Microfinance Bank',
    slug: '',
    code: '594',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Aztec Microfinance Bank',
    slug: '',
    code: '654',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Baines Credit Microfinance Bank',
    slug: '',
    code: '393',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Balera Microfinance Bank Ltd',
    slug: '',
    code: '677',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Balogun Fulani Microfinance Bank',
    slug: '',
    code: '390',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Balogun Gambari Microfinance Bank',
    slug: '',
    code: '469',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Banc Corp Microfinance Bank',
    slug: '',
    code: '694',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Banex Microfinance Bank',
    slug: '',
    code: '545',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Bankeasy MFB',
    slug: '',
    code: '1025',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Bankit MFB',
    slug: '',
    code: '428',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Bankly Microfinance Bank',
    slug: '',
    code: '644',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Baobab Microfinance Bank',
    slug: '',
    code: '344',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Barnawa MFB',
    slug: '',
    code: '1023',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Bayero Microfinance Bank',
    slug: '',
    code: '459',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'BC Kash Microfinance Bank',
    slug: '',
    code: '335',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Benysta Microfinance Bank',
    slug: '',
    code: '533',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Beststar Microfinance Bank',
    slug: '',
    code: '719',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Beta-Access Yello',
    slug: '',
    code: '794',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Bipc Microfinance Bank',
    slug: '',
    code: '478',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Bishopgate Microfinance Bank',
    slug: '',
    code: '669',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Blackthorn Finance',
    slug: '',
    code: '856',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Bloom MFB',
    slug: '',
    code: '843',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Blue Investments Microfinance Bank',
    slug: '',
    code: '652',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Bluewhales Microfinance Bank',
    slug: '',
    code: '551',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Boctrust Microfinance Bank',
    slug: '',
    code: '325',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Boi Mf Bank',
    slug: '',
    code: '563',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Boji Boji Microfinance Bank',
    slug: '',
    code: '610',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Bold Microfinance Bank',
    slug: '',
    code: '926',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Bonghe Microfinance Bank',
    slug: '',
    code: '462',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Borgu Microfinance Bank',
    slug: '',
    code: '516',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Borno Renaissance Microfinance Bank',
    slug: '',
    code: '624',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Boromu Microfinance Bank',
    slug: '',
    code: '617',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Borstal Microfinance Bank',
    slug: '',
    code: '572',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Bosak Microfinance Bank',
    slug: '',
    code: '384',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Bowen Microfinance Bank',
    slug: 'bowen-microfinance-bank',
    code: '50931',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Branch International Finance Company Limited',
    slug: '',
    code: '269',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Brent Mortgage Bank',
    slug: '',
    code: '298',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Brethren Microfinance Bank',
    slug: '',
    code: '444',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Bridgeway Microfinance Bank',
    slug: '',
    code: '514',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Brightway Microfinance Bank',
    slug: '',
    code: '456',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Broadview Microfinance Bank Ltd',
    slug: '',
    code: '682',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Bubayero Microfinance Bank',
    slug: '',
    code: '628',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Bud Infrastructure Limited',
    slug: '',
    code: '814',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Business Support Microfinance Bank',
    slug: '',
    code: '527',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Calabar Microfinance Bank',
    slug: '',
    code: '535',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Capitalmetriq Swift Microfinance Bank',
    slug: '',
    code: '625',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Capricorn Digital',
    slug: '',
    code: '816',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Capstone Mf Bank',
    slug: '',
    code: '564',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Carbon',
    slug: '',
    code: '782',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Caretaker Microfinance Bank',
    slug: '',
    code: '588',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Cashbridge Microfinance Bank',
    slug: '',
    code: '724',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Cashconnect Microfinance Bank',
    slug: '',
    code: '490',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Cashrite Microfinance Bank',
    slug: '',
    code: '726',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Catland Microfinance Bank',
    slug: '',
    code: '614',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'CBN_TSA',
    slug: '',
    code: '854',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Cedar Microfinance Bank Ltd',
    slug: '',
    code: '676',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Cellulant',
    slug: '',
    code: '761',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Cellulant Pssp',
    slug: '',
    code: '807',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'CEMCS Microfinance Bank',
    slug: 'cemcs-microfinance-bank',
    code: '50823',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/cemcs-microfinance-bank.png',
  },
  {
    name: 'Central Bank Of Nigeria',
    slug: '',
    code: '249',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'CENTRUM FINANCE',
    slug: '',
    code: '839',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'ChamsMobile',
    slug: '',
    code: '835',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Chanelle Bank',
    slug: '',
    code: '518',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Chase Microfinance Bank',
    slug: '',
    code: '638',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Cherish Microfinance Bank',
    slug: '',
    code: '560',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Chibueze Microfinance Bank',
    slug: '',
    code: '536',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Chikum Microfinance Bank',
    slug: '',
    code: '349',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Chukwunenye Microfinance Bank',
    slug: '',
    code: '606',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Citibank Nigeria',
    slug: 'citibank-nigeria',
    code: '023',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/citibank-nigeria.png',
  },
  {
    name: 'Citizen Trust Microfinance Bank Ltd',
    slug: '',
    code: '484',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'CIT Microfinance Bank',
    slug: '',
    code: '352',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Clearpay Microfinance Bank',
    slug: '',
    code: '598',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Cloverleaf Microfinance Bank',
    slug: '',
    code: '627',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Coalcamp Microfinance Bank',
    slug: '',
    code: '410',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Coastline Microfinance Bank',
    slug: '',
    code: '501',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Confidence Microfinance Bank Ltd',
    slug: '',
    code: '645',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Consistent Trust Microfinance Bank Ltd',
    slug: '',
    code: '667',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Consumer Microfinance Bank',
    slug: '',
    code: '338',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Coop Mortgage Bank',
    slug: '',
    code: '302',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Corestep Microfinance Bank',
    slug: '',
    code: '494',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Coronation Merchant Bank',
    slug: '',
    code: '281',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'County Finance Ltd',
    slug: '',
    code: '264',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Covenant Microfinance Bank',
    slug: '',
    code: '289',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Credit Afrique Microfinance Bank',
    slug: '',
    code: '367',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Credit Direct Limited',
    slug: '',
    code: '824',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Creditville Microfinance Bank',
    slug: '',
    code: '715',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Crescent Microfinance Bank',
    slug: '',
    code: '641',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Crossriver Microfinance Bank',
    slug: '',
    code: '549',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Crowdforce',
    slug: '',
    code: '811',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Crutech Microfinance Bank',
    slug: '',
    code: '534',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Cyberspace Limited',
    slug: '',
    code: '809',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Davodani Microfinance Bank',
    slug: '',
    code: '512',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Daylight Microfinance Bank',
    slug: '',
    code: '375',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Delta Trust Mortgage Bank',
    slug: '',
    code: '304',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Destiny MFB',
    slug: '',
    code: '741',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Digitvant MFB',
    slug: '',
    code: '754',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Dignity Finance',
    slug: '',
    code: '275',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Dot Microfinance Bank',
    slug: '',
    code: '586',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'DW MFB',
    slug: '',
    code: '740',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Eagle Flight Microfinance Bank',
    slug: '',
    code: '445',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Eartholeum',
    slug: '',
    code: '777',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'e-Barcs Microfinance Bank',
    slug: '',
    code: '364',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ebsu Microfinance Bank',
    slug: '',
    code: '547',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ecobank Nigeria',
    slug: 'ecobank-nigeria',
    code: '050',
    ussd: '*326#',
    logo: 'https://nigerianbanks.xyz/logo/ecobank-nigeria.png',
  },
  {
    name: 'Ecobank Xpress Account',
    slug: '',
    code: '764',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'EcoMobile',
    slug: '',
    code: '786',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Edfin Microfinance Bank',
    slug: '',
    code: '457',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Egwafin Microfinance Bank Ltd',
    slug: '',
    code: '670',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ekimogun Microfinance Bank',
    slug: '',
    code: '666',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ekondo Microfinance Bank',
    slug: 'ekondo-microfinance-bank',
    code: '562',
    ussd: '*540*178#',
    logo: 'https://nigerianbanks.xyz/logo/ekondo-microfinance-bank.png',
  },
  {
    name: 'Ek-Reliable Microfinance Bank',
    slug: '',
    code: '510',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Emeralds Microfinance Bank',
    slug: '',
    code: '426',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Empire trust MFB',
    slug: '',
    code: '322',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'ENaira',
    slug: '',
    code: '253',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Enco Finance',
    slug: '',
    code: '274',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Enrich Microfinance Bank',
    slug: '',
    code: '653',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Enterprise Bank',
    slug: '',
    code: '246',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Esan Microfinance Bank',
    slug: '',
    code: '394',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Eso-E Microfinance Bank',
    slug: '',
    code: '374',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'eTranzact',
    slug: '',
    code: '762',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Evangel Microfinance Bank',
    slug: '',
    code: '453',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Evergreen Microfinance Bank',
    slug: '',
    code: '475',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Evib Finance',
    slug: '',
    code: '1015',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ewt Microfinance Bank',
    slug: '',
    code: '686',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Excellent Microfinance Bank',
    slug: '',
    code: '655',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Eyowo MFB',
    slug: '',
    code: '471',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Fairmoney Microfinance Bank Ltd',
    slug: '',
    code: '665',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Fame Microfinance Bank',
    slug: '',
    code: '473',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Fast Credit',
    slug: '',
    code: '272',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Fast Microfinance Bank',
    slug: '',
    code: '388',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'FBNMobile',
    slug: '',
    code: '770',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'FBNQUEST Merchant Bank',
    slug: '',
    code: '282',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'FCMB Easy Account',
    slug: '',
    code: '787',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Fcmb Microfinance Bank',
    slug: '',
    code: '529',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Fct Microfinance Bank',
    slug: '',
    code: '441',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Federalpoly Nasarawamfb',
    slug: '',
    code: '449',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Federal Polytechnic Nekede Microfinance Bank',
    slug: '',
    code: '519',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'FET',
    slug: '',
    code: '758',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Fewchore Finance Company Limited',
    slug: '',
    code: '265',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'FFS Microfinance Bank',
    slug: '',
    code: '361',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Fha Mortgage Bank Ltd',
    slug: '',
    code: '307',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Fidelity Bank',
    slug: 'fidelity-bank',
    code: '070',
    ussd: '*770#',
    logo: 'https://nigerianbanks.xyz/logo/fidelity-bank.png',
  },
  {
    name: 'Fidfund Microfinance Bank',
    slug: '',
    code: '334',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Fims Microfinance Bank',
    slug: '',
    code: '623',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Finatrust Microfinance Bank',
    slug: '',
    code: '841',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Finca Microfinance Bank',
    slug: '',
    code: '521',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Firmus MFB',
    slug: '',
    code: '495',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'First Apple Limited',
    slug: '',
    code: '799',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'First Bank of Nigeria',
    slug: 'first-bank-of-nigeria',
    code: '011',
    ussd: '*894#',
    logo: 'https://nigerianbanks.xyz/logo/first-bank-of-nigeria.png',
  },
  {
    name: 'First City Monument Bank',
    slug: 'first-city-monument-bank',
    code: '214',
    ussd: '*329#',
    logo: 'https://nigerianbanks.xyz/logo/first-city-monument-bank.png',
  },
  {
    name: 'First Generation Mortgage Bank',
    slug: '',
    code: '297',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'First Heritage Microfinance Bank',
    slug: '',
    code: '595',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Firstmidas Microfinance Bank Ltd',
    slug: '',
    code: '689',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'First Multiple Microfinance Bank',
    slug: '',
    code: '371',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'First Option Microfinance Bank',
    slug: '',
    code: '437',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'First Royal Microfinance Bank',
    slug: '',
    code: '372',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Firsttrust Mortgage Bank',
    slug: '',
    code: '317',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Flourish MFB',
    slug: '',
    code: '718',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Flutterwave Technology Solutions Limited',
    slug: '',
    code: '797',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Focus Microfinance Bank',
    slug: '',
    code: '735',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Foresight Microfinance Bank',
    slug: '',
    code: '637',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Fortis Microfinance Bank',
    slug: '',
    code: '288',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'FortisMobile',
    slug: '',
    code: '772',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Fortress Microfinance Bank',
    slug: '',
    code: '602',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'FSDH Merchant Bank',
    slug: '',
    code: '838',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'FUD MFB',
    slug: '',
    code: '461',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Fullrange Microfinance Bank',
    slug: '',
    code: '353',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Fundquest Financial Services Ltd',
    slug: '',
    code: '273',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Futminna Microfinance Bank',
    slug: '',
    code: '558',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Futo Microfinance Bank',
    slug: '',
    code: '366',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Gabsyn Microfinance Bank',
    slug: '',
    code: '702',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Gadol Finance',
    slug: '',
    code: '1014',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Garki Microfinance Bank',
    slug: '',
    code: '600',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Gashua Microfinance Bank',
    slug: '',
    code: '376',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Gateway Mortgage Bank',
    slug: '',
    code: '292',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Gbede Microfinance Bank',
    slug: '',
    code: '692',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Giant Stride Microfinance Bank',
    slug: '',
    code: '591',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Gidauniyar Alheri Microfinance Bank',
    slug: '',
    code: '722',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Giginya Microfinance Bank',
    slug: '',
    code: '531',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Girei Microfinance Bank',
    slug: '',
    code: '392',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Giwa Microfinance Bank',
    slug: '',
    code: '561',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Globus Bank',
    slug: 'globus-bank',
    code: '00103',
    ussd: '*989#',
    logo: 'https://nigerianbanks.xyz/logo/globus-bank.png',
  },
  {
    name: 'Glory Microfinance Bank',
    slug: '',
    code: '431',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Gmb Microfinance Bank',
    slug: '',
    code: '528',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Goldman Microfinance Bank',
    slug: '',
    code: '688',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Gombe Microfinance Bank Ltd',
    slug: '',
    code: '697',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'GoMoney',
    slug: '',
    code: '778',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Good Neighbours Microfinance Bank',
    slug: '',
    code: '583',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Gowans Microfinance Bank',
    slug: '',
    code: '330',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Grant MF Bank',
    slug: '',
    code: '477',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Greenacres MFB',
    slug: '',
    code: '706',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'GreenBank Microfinance Bank',
    slug: '',
    code: '387',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Green Energy Microfinance Bank Ltd',
    slug: '',
    code: '664',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Greenville Microfinance Bank',
    slug: '',
    code: '422',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Greenwich Merchant Bank',
    slug: '',
    code: '284',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Grooming Microfinance Bank',
    slug: '',
    code: '400',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Gti Microfinance Bank',
    slug: '',
    code: '508',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'GTMobile',
    slug: '',
    code: '765',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Guaranty Trust Bank',
    slug: 'guaranty-trust-bank',
    code: '058',
    ussd: '*737#',
    logo: 'https://nigerianbanks.xyz/logo/guaranty-trust-bank.png',
  },
  {
    name: 'Gwong Microfinance Bank',
    slug: '',
    code: '616',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Hackman Microfinance Bank',
    slug: '',
    code: '355',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Haggai Mortgage Bank Limited',
    slug: '',
    code: '300',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Halacredit Microfinance Bank',
    slug: '',
    code: '442',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Hasal Microfinance Bank',
    slug: 'hasal-microfinance-bank',
    code: '50383',
    ussd: '*322*127#',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Headway Microfinance Bank',
    slug: '',
    code: '492',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Hedonmark',
    slug: '',
    code: '773',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Heritage Bank',
    slug: 'heritage-bank',
    code: '030',
    ussd: '*322#',
    logo: 'https://nigerianbanks.xyz/logo/heritage-bank.png',
  },
  {
    name: 'Highland Microfinance Bank',
    slug: '',
    code: '538',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Hillpost MFB',
    slug: '',
    code: '848',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Homebase Mortgage',
    slug: '',
    code: '305',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Hopepsb',
    slug: '',
    code: '826',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'IBA MFB',
    slug: '',
    code: '705',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'IBANK Microfinance Bank',
    slug: '',
    code: '323',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'IBBU MFB',
    slug: '',
    code: '730',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ibeto Microfinance Bank',
    slug: '',
    code: '559',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'IBILE Microfinance Bank',
    slug: '',
    code: '326',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ibolo Micorfinance Bank Ltd',
    slug: '',
    code: '647',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ibom Fadama Microfinance Bank',
    slug: '',
    code: '635',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ibu-Aje Microfinance',
    slug: '',
    code: '604',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ic Globalmicrofinance Bank',
    slug: '',
    code: '636',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Igbo-ukwu MFB',
    slug: '',
    code: '1028',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ihiala MFB',
    slug: '',
    code: '743',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ijare MFB',
    slug: '',
    code: '745',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ijebu-Ife Microfinance Bank Ltd',
    slug: '',
    code: '660',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ikenne Microfinance Bank',
    slug: '',
    code: '467',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ikere MFB',
    slug: '',
    code: '1026',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ikire Microfinance Bank',
    slug: '',
    code: '432',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ikoyi-Osun Microfinance Bank',
    slug: '',
    code: '650',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ilaro Poly Microfinance Bank Ltd',
    slug: '',
    code: '685',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ilasan Microfinance Bank',
    slug: '',
    code: '497',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Illorin Microfinance Bank',
    slug: '',
    code: '487',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ilora Microfinance Bank',
    slug: '',
    code: '550',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Imo State Microfinance Bank',
    slug: '',
    code: '411',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Imowo Microfinance Bank',
    slug: '',
    code: '537',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Imperial Homes Mortgage Bank',
    slug: '',
    code: '780',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Indulge Microfinance Bank',
    slug: '',
    code: '1011',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Infinity Microfinance Bank',
    slug: '',
    code: '365',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Infinity Trust Mortgage Bank',
    slug: '',
    code: '299',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Innovectives Kesh',
    slug: '',
    code: '785',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Insight Microfinance Bank',
    slug: '',
    code: '554',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Intellifin',
    slug: '',
    code: '783',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Interland Microfinance Bank',
    slug: '',
    code: '509',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Interswitch Financial Inclusion Services (Ifis)',
    slug: '',
    code: '805',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Interswitch Limited',
    slug: '',
    code: '798',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Iperu Microfinance Bank',
    slug: '',
    code: '609',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'IRL Microfinance Bank',
    slug: '',
    code: '357',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Isaleoyo Microfinance Bank',
    slug: '',
    code: '503',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ishie Microfinance Bank',
    slug: '',
    code: '548',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Island Microfinance Bank',
    slug: '',
    code: '696',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Isua Microfinance Bank',
    slug: '',
    code: '732',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Isuofia Microfinance Bank',
    slug: '',
    code: '489',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Itex Integrated Services Limited',
    slug: '',
    code: '407',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Iwade Microfinance Bank Ltd',
    slug: '',
    code: '691',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Iwoama Microfinance Bank',
    slug: '',
    code: '657',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Iyamoye Microfinance Bank Ltd',
    slug: '',
    code: '684',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },

  {
    name: 'Jaiz Bank',
    slug: 'jaiz-bank',
    code: '301',
    ussd: '*773#',
    logo: 'https://nigerianbanks.xyz/logo/jaiz-bank.png',
  },
  {
    name: 'Jamb Microfinance Bank',
    slug: '',
    code: '552',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Jega Microfinance Bank',
    slug: '',
    code: '532',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Jengre Microfinance Bank',
    slug: '',
    code: '622',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Jubilee Life Mortgage Bank',
    slug: '',
    code: '295',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Kadpoly Microfinance Bank',
    slug: '',
    code: '463',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Kankara Microfinance Bank',
    slug: '',
    code: '1024',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Kanopoly Microfinance Bank',
    slug: '',
    code: '464',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'KCMB Microfinance Bank',
    slug: '',
    code: '329',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Keystone Bank',
    slug: 'keystone-bank',
    code: '082',
    ussd: '*7111#',
    logo: 'https://nigerianbanks.xyz/logo/keystone-bank.png',
  },
  {
    name: 'Kontagora Microfinance Bank',
    slug: '',
    code: '466',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Koraypay',
    slug: '',
    code: '821',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Kredi Money Microfinance Bank',
    slug: '',
    code: '522',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Kuda Microfinance Bank',
    slug: 'kuda',
    code: '50211',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/kuda.png',
  },
  {
    name: 'Kwasu Microfinance Bank',
    slug: '',
    code: '580',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Lagos Building Investment Company',
    slug: '',
    code: '296',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Landgold Microfinance Bank',
    slug: '',
    code: '470',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'LAPO Microfinance Bank',
    slug: '',
    code: '343',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Lavender Microfinance Bank',
    slug: '',
    code: '433',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Leadcity Microfinance Bank',
    slug: '',
    code: '584',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Legend Microfinance Bank',
    slug: '',
    code: '485',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Lekki Microfinance Bank',
    slug: '',
    code: '1010',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Letshego Microfinance Bank',
    slug: '',
    code: '346',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Lifegate Microfinance Bank',
    slug: '',
    code: '708',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Lifegate Microfinance Bank Ltd',
    slug: '',
    code: '1012',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Light Microfinance Bank',
    slug: '',
    code: '1009',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Links Microfinance Bank',
    slug: '',
    code: '1013',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Livingtrust Mortgage Bank',
    slug: '',
    code: '294',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Lotas Microfinance Bank',
    slug: '',
    code: '1008',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Lovonus Microfinance Bank',
    slug: '',
    code: '378',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Lush Microfinance Bank',
    slug: '',
    code: '1007',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Macrod Microfinance Bank',
    slug: '',
    code: '1006',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Mainstreet Microfinance Bank',
    slug: '',
    code: '327',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Malachy Microfinance Bank',
    slug: '',
    code: '1005',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Maritime Microfinance Bank',
    slug: '',
    code: '1004',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Mayfair Microfinance Bank',
    slug: '',
    code: '379',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Mayfresh Mortgage Bank',
    slug: '',
    code: '311',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Mcafee Microfinance Bank',
    slug: '',
    code: '1003',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Megapraise Microfinance Bank',
    slug: '',
    code: '419',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Meridian Microfinance Bank',
    slug: '',
    code: '1002',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Microcred Microfinance Bank',
    slug: '',
    code: '333',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Microvis Microfinance Bank',
    slug: '',
    code: '331',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Midland Microfinance Bank',
    slug: '',
    code: '381',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Mkobo Microfinance Bank',
    slug: '',
    code: '1001',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'MKOBO Microfinance Bank',
    slug: '',
    code: '511',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'MKOBO MFB',
    slug: '',
    code: '845',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Mogimo Microfinance Bank',
    slug: '',
    code: '1000',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Moneytrust Microfinance Bank',
    slug: '',
    code: '999',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Moniepoint Microfinance Bank',
    slug: '',
    code: '50515',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Moyofade Microfinance Bank',
    slug: '',
    code: '998',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Mutual Benefits Microfinance Bank',
    slug: '',
    code: '382',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Mutual Trust Microfinance Bank',
    slug: '',
    code: '332',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Nargarta Microfinance Bank',
    slug: '',
    code: '997',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Navy Microfinance Bank',
    slug: '',
    code: '996',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ndiorah Microfinance Bank',
    slug: '',
    code: '995',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Nefatari Microfinance Bank',
    slug: '',
    code: '994',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'New Dawn Microfinance Bank',
    slug: '',
    code: '416',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'New Golden Microfinance Bank',
    slug: '',
    code: '993',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'New Women Microfinance Bank',
    slug: '',
    code: '992',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Nigerian Prisons Microfinance Bank',
    slug: '',
    code: '991',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Nigerian Navy Microfinance Bank',
    slug: '',
    code: '990',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'NIRSAL Microfinance Bank',
    slug: '',
    code: '989',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Nnoboa Microfinance Bank',
    slug: '',
    code: '988',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Nova Merchant Bank',
    slug: '',
    code: '283',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'NowNow Digital Systems Limited',
    slug: '',
    code: '987',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Npf Microfinance Bank',
    slug: '',
    code: '354',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Nsehe Microfinance Bank',
    slug: '',
    code: '986',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Numo Microfinance Bank',
    slug: '',
    code: '985',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Nus Microfinance Bank',
    slug: '',
    code: '984',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Oakland Microfinance Bank',
    slug: '',
    code: '983',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Oche Microfinance Bank',
    slug: '',
    code: '982',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ode Microfinance Bank',
    slug: '',
    code: '981',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ogige Microfinance Bank',
    slug: '',
    code: '980',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ogun State Saving And Loans Limited',
    slug: '',
    code: '979',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ohha Microfinance Bank',
    slug: '',
    code: '360',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Olofin Owena Microfinance Bank',
    slug: '',
    code: '978',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Oluchukwu Microfinance Bank',
    slug: '',
    code: '359',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Oluyole Microfinance Bank',
    slug: '',
    code: '977',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Omiye Microfinance Bank',
    slug: '',
    code: '976',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Omni Microfinance Bank',
    slug: '',
    code: '975',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'One Finance',
    slug: '',
    code: '271',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Opay Digital Services',
    slug: '',
    code: '974',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Oroke Microfinance Bank',
    slug: '',
    code: '973',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ospoly Microfinance Bank',
    slug: '',
    code: '972',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Otech Microfinance Bank',
    slug: '',
    code: '971',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Owerri Microfinance Bank',
    slug: '',
    code: '970',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Owhworhukwo Microfinance Bank',
    slug: '',
    code: '969',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Page Financials',
    slug: '',
    code: '270',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Palm Pay',
    slug: '',
    code: '968',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Pama Microfinance Bank',
    slug: '',
    code: '967',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Pankan Microfinance Bank',
    slug: '',
    code: '966',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Parallex Bank',
    slug: 'parallex-bank',
    code: '104',
    ussd: '*574#',
    logo: 'https://nigerianbanks.xyz/logo/parallex-bank.png',
  },
  {
    name: 'Parkway-ReadyCash',
    slug: '',
    code: '766',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Pecantrust Microfinance Bank',
    slug: '',
    code: '965',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Pennywise Microfinance Bank',
    slug: '',
    code: '964',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Personal Trust Microfinance Bank',
    slug: '',
    code: '350',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Petra Microfinance Bank',
    slug: '',
    code: '356',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Pfs MFB',
    slug: '',
    code: '964',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Pillar Microfinance Bank',
    slug: '',
    code: '963',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Platinum Mortgage Bank',
    slug: '',
    code: '303',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Polaris Bank',
    slug: 'polaris-bank',
    code: '076',
    ussd: '*833#',
    logo: 'https://nigerianbanks.xyz/logo/polaris-bank.png',
  },
  {
    name: 'Polybadan Microfinance Bank',
    slug: '',
    code: '962',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Polyunwana Microfinance Bank',
    slug: '',
    code: '961',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Preeminent Microfinance Bank',
    slug: '',
    code: '960',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Premiumtrust Bank',
    slug: '',
    code: '105',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Prestanova MFB',
    slug: '',
    code: '959',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Presto Integrated Microfinance Bank',
    slug: '',
    code: '958',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Prudential Microfinance Bank',
    slug: '',
    code: '957',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Pukan Microfinance Bank',
    slug: '',
    code: '956',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Purplemoney Microfinance Bank',
    slug: '',
    code: '955',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Pwan Microfinance Bank',
    slug: '',
    code: '954',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Qube MFB',
    slug: '',
    code: '953',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Quickfund Microfinance Bank',
    slug: '',
    code: '952',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Radalpha Microfinance Bank',
    slug: '',
    code: '951',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Rand Merchant Bank',
    slug: '',
    code: '286',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Rano Microfinance Bank',
    slug: '',
    code: '950',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Refuge Mortgage Bank',
    slug: '',
    code: '308',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Regent Microfinance Bank',
    slug: '',
    code: '351',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Reliance Microfinance Bank',
    slug: '',
    code: '949',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Renmoney Microfinance Bank',
    slug: '',
    code: '948',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Richway Microfinance Bank',
    slug: '',
    code: '348',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Rima Microfinance Bank',
    slug: '',
    code: '947',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Rima Growth Pathway Microfinance Bank',
    slug: '',
    code: '946',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Rockshield Microfinance Bank',
    slug: '',
    code: '945',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Royal Blue Microfinance Bank',
    slug: '',
    code: '944',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Royal Exchange Microfinance Bank',
    slug: '',
    code: '336',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Rubies Microfinance Bank',
    slug: '',
    code: '943',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Safe Haven Microfinance Bank',
    slug: '',
    code: '337',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Safegate Microfinance Bank',
    slug: '',
    code: '942',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Safeswitch Microfinance Bank',
    slug: '',
    code: '941',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Sagamu Microfinance Bank',
    slug: '',
    code: '340',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Sail Microfinance Bank',
    slug: '',
    code: '940',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Satin Bake Microfinance Bank',
    slug: '',
    code: '939',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Seed Capital Microfinance Bank',
    slug: '',
    code: '338',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Seedvest Microfinance Bank',
    slug: '',
    code: '938',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Shalom Microfinance Bank',
    slug: '',
    code: '937',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Shield Microfinance Bank',
    slug: '',
    code: '936',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Signature Bank',
    slug: '',
    code: '106',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Skye Microfinance Bank',
    slug: '',
    code: '935',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Solid Allianze Microfinance Bank',
    slug: '',
    code: '934',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Solidrock Microfinance Bank',
    slug: '',
    code: '933',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Source Microfinance Bank',
    slug: '',
    code: '932',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Sparkle',
    slug: '',
    code: '767',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Stanbic IBTC',
    slug: 'stanbic-ibtc-bank',
    code: '221',
    ussd: '*909#',
    logo: 'https://nigerianbanks.xyz/logo/stanbic-ibtc-bank.png',
  },
  {
    name: 'Stanbic IBTC Mobile',
    slug: '',
    code: '771',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Standard Chartered Bank',
    slug: 'standard-chartered-bank',
    code: '068',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/standard-chartered-bank.png',
  },
  {
    name: 'Stanford Microfinance Bank',
    slug: '',
    code: '931',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Stellas Microfinance Bank',
    slug: '',
    code: '930',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Sterling Bank',
    slug: 'sterling-bank',
    code: '232',
    ussd: '*822#',
    logo: 'https://nigerianbanks.xyz/logo/sterling-bank.png',
  },
  {
    name: 'Sulsap Microfinance Bank',
    slug: '',
    code: '929',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Sunbeam Microfinance Bank',
    slug: '',
    code: '928',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Suntrust Bank',
    slug: 'suntrust-bank',
    code: '100',
    ussd: '*5230#',
    logo: 'https://nigerianbanks.xyz/logo/suntrust-bank.png',
  },
  {
    name: 'Sustained Microfinance Bank',
    slug: '',
    code: '927',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Taj Bank',
    slug: 'taj-bank',
    code: '302',
    ussd: '*898#',
    logo: 'https://nigerianbanks.xyz/logo/taj-bank.png',
  },
  {
    name: 'TASUED Microfinance Bank',
    slug: '',
    code: '926',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'TCF Microfinance Bank',
    slug: '',
    code: '358',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Teamapt Limited',
    slug: '',
    code: '803',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Titan Trust Bank',
    slug: 'titan-trust-bank',
    code: '102',
    ussd: '*922#',
    logo: 'https://nigerianbanks.xyz/logo/titan-trust-bank.png',
  },
  {
    name: 'Titan-Paystack',
    slug: '',
    code: '774',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Trident Microfinance Bank',
    slug: '',
    code: '925',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Trust Microfinance Bank',
    slug: '',
    code: '924',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Trustbond Mortgage Bank',
    slug: '',
    code: '310',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Trustfund Microfinance Bank',
    slug: '',
    code: '923',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'U and C Microfinance Bank',
    slug: '',
    code: '922',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Uda Microfinance Bank',
    slug: '',
    code: '921',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Ummah Microfinance Bank',
    slug: '',
    code: '920',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Unaab Microfinance Bank',
    slug: '',
    code: '919',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Uniben Microfinance Bank',
    slug: '',
    code: '918',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Unical Microfinance Bank',
    slug: '',
    code: '917',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Unify Microfinance Bank',
    slug: '',
    code: '916',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Union Bank of Nigeria',
    slug: 'union-bank-of-nigeria',
    code: '032',
    ussd: '*826#',
    logo: 'https://nigerianbanks.xyz/logo/union-bank-of-nigeria.png',
  },
  {
    name: 'United Bank for Africa',
    slug: 'united-bank-for-africa',
    code: '033',
    ussd: '*919#',
    logo: 'https://nigerianbanks.xyz/logo/united-bank-for-africa.png',
  },
  {
    name: 'Unity Bank',
    slug: 'unity-bank',
    code: '215',
    ussd: '*7799#',
    logo: 'https://nigerianbanks.xyz/logo/unity-bank.png',
  },
  {
    name: 'Unn Microfinance Bank',
    slug: '',
    code: '915',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'VFD Microfinance Bank',
    slug: '',
    code: '914',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Viva Microfinance Bank',
    slug: '',
    code: '913',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Waya Microfinance Bank',
    slug: '',
    code: '912',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Wema Bank',
    slug: 'wema-bank',
    code: '035',
    ussd: '*945#',
    logo: 'https://nigerianbanks.xyz/logo/wema-bank.png',
  },
  {
    name: 'Wetland Microfinance Bank',
    slug: '',
    code: '911',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Xpress Payments',
    slug: '',
    code: '910',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Yct Microfinance Bank',
    slug: '',
    code: '909',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Yobe Microfinance Bank',
    slug: '',
    code: '908',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Zankli Microfinance Bank',
    slug: '',
    code: '907',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
  {
    name: 'Zenith Bank',
    slug: 'zenith-bank',
    code: '057',
    ussd: '*966#',
    logo: 'https://nigerianbanks.xyz/logo/zenith-bank.png',
  },
  {
    name: 'ZenithMobile',
    slug: '',
    code: '768',
    ussd: '',
    logo: 'https://nigerianbanks.xyz/logo/default-image.png',
  },
];
