export enum PaymentErrorEnum {
  COUNTRY_NOT_SUPPORTED = 'COUNTRY_NOT_SUPPORTED',
  COUNTRY_NOT_ACTIVE = 'COUNTRY_NOT_ACTIVE',
  RATES_NOT_YET_ACTIVE = 'RATES_NOT_YET_ACTIVE',
}

export enum PaymentPartnerEnum {
  YELLOWCARD = 'YELLOWCARD',
  KOTANIPAY = 'KOTANIPAY',
  CIRCLE = 'CIRCLE',
}
