export enum PaymentErrorEnum {
  INSUFFICIENT_FUNDS = 'payments/INSUFFICIENT_FUNDS',
  INVALID_ADDRESS = 'payments/INVALID_ADDRESS',
  NETWORK_NOT_SUPPORTED = 'payments/NETWORK_NOT_SUPPORTED',
  TOKEN_NOT_FOUND = 'payments/TOKEN_NOT_FOUND',
  PAYMENT_LIMIT_EXCEEDED = 'payments/LIMIT_EXCEEDED',
  DUPLICATE_REQUEST = 'payments/DUPLICATE_REQUEST',
  WITHDRAWAL_BLOCKED = 'payments/WITHDRAWAL_BLOCKED',
  UNKNOWN = 'payments/UNKNOWN',
}
