export enum SettingsErrorEnum {
  STORE_SETTINGS_NOT_FOUND = 'STORE_SETTINGS_NOT_FOUND',
  TAX_SETTINGS_INVALID = 'TAX_SETTINGS_INVALID',
  PAYMENT_SETTINGS_INVALID = 'PAYMENT_SETTINGS_INVALID',
  PAYOUT_SETTINGS_INVALID = 'PAYOUT_SETTINGS_INVALID',
  SETTINGS_UPDATE_FAILED = 'SETTINGS_UPDATE_FAILED',
}

export enum BankAccountErrorEnum {
  BANK_ACCOUNT_NOT_FOUND = 'BANK_ACCOUNT_NOT_FOUND',
  BANK_ACCOUNT_ALREADY_EXISTS = 'BANK_ACCOUNT_ALREADY_EXISTS',
  INVALID_ACCOUNT_NUMBER = 'INVALID_ACCOUNT_NUMBER',
  FAILED_TO_CREATE_BANK_ACCOUNT = 'FAILED_TO_CREATE_BANK_ACCOUNT',
  FAILED_TO_UPDATE_BANK_ACCOUNT = 'FAILED_TO_UPDATE_BANK_ACCOUNT',
  FAILED_TO_DELETE_BANK_ACCOUNT = 'FAILED_TO_DELETE_BANK_ACCOUNT',
}
