export enum UserErrorEnum {
  EMAIL_EXISTS = 'EMAIL_EXISTS',
  BRAND_EXISTS = 'BRAND_EXISTS',
  REJECTED_AGREEMENT = 'REJECTED_AGREEMENT',
  INVALID_CREDENTIAL = 'INVALID_CREDENTIAL',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  PHONE_NOT_VERIFIED = 'PHONE_NOT_VERIFIED',
}
