export enum UserErrorEnum {
  EMAIL_EXISTS = 'access/EMAIL_EXISTS',
  BRAND_EXISTS = 'access/BRAND_EXISTS',
  REJECTED_AGREEMENT = 'access/REJECTED_AGREEMENT',
  INVALID_CREDENTIAL = 'access/INVALID_CREDENTIAL',
  EMAIL_NOT_VERIFIED = 'access/EMAIL_NOT_VERIFIED',
  PHONE_NOT_VERIFIED = 'access/PHONE_NOT_VERIFIED',
  INVALID_EMAIL_FORMAT = 'access/INVALID_EMAIL_FORMAT',
  CODE_ALREADY_SENT = 'access/CODE_ALREADY_SENT',
  USER_NOT_FOUND = 'access/USER_NOT_FOUND',
  USER_SUSPENDED = 'access/USER_SUSPENDED',
  UNAUTHORIZED = 'access/UNAUTHORIZED',
  FORBIDDEN = 'access/FORBIDDEN',
}
